version: '3.8'
services:
  db:
    container_name: dbcon
    build:
      context: .
      dockerfile: ./dockerfiles/db/Dockerfile.db
    volumes:
      - data:/var/lib/postgresql/data
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./dockerfiles/app/Dockerfile
    ports:
    - 8080:8080
    depends_on:
      - db
volumes:
  data: